### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by kaosdev** [vickychijwani/kotlin-koans-android#2] opened 2017-12-14 18:48 UTC
Whenever I click on compile I only get "an error occurred" message. Internet working well, that's strange cause it started randomly, not after an update, but when using the app, and now it's always here.  Also tried uninstalling, clearing cache and data's, but nothing.

**Comment by vickychijwani** [comment] 2017-12-15 07:28
Hi! :wave:

I'm able to reproduce your issue. This app uses the API used by http://try.kotl.in. Most likely the API behaviour has changed in some way causing requests to fail.

Unfortunately I won't have access to a computer for the next 2 weeks, so it might be a while before I can fix this.

**Comment by vickychijwani** [comment] 2017-12-31 12:50
Hi again @kaos-dev!

The issue is fixed in v1.2.0 of the app via commit https://github.com/vickychijwani/kotlin-koans-android/commit/a3252c5c2e2ac6c1b614b21104fce183895de671. Please update it and let me know if you still see errors 😄

**Closed as completed by vickychijwani** 2017-12-31 12:50 UTC
